apiVersion: v1
kind: Secret
metadata:
  name: external-dns
  namespace: external-dns
stringData:
  ARM_REGION: $cndi_on_ow.seal_secret_from_env_var(ARM_REGION)
  ARM_SUBSCRIPTION_ID: $cndi_on_ow.seal_secret_from_env_var(ARM_SUBSCRIPTION_ID)
  ARM_CLIENT_ID: $cndi_on_ow.seal_secret_from_env_var(ARM_CLIENT_ID)
  ARM_CLIENT_SECRET: $cndi_on_ow.seal_secret_from_env_var(ARM_CLIENT_SECRET)
  ARM_TENANT_ID: $cndi_on_ow.seal_secret_from_env_var(ARM_TENANT_ID)